name = "HydroModelMCP"
uuid = "b04cb046-4fd7-4b4f-8949-f07de8180241"
version = "0.1.0"
authors = ["jing xin <50790703+chooron@users.noreply.github.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DotEnv = "4dc1fcf4-5e3b-5448-94ab-0c38ec0385c1"
GlobalSensitivity = "af5da776-676b-467e-8baf-acd8249e4f0f"
HydroModelLibrary = "f34bc7f3-9d04-4ef8-b7a3-feb87ce2ba93"
HydroModels = "7e3cde01-c141-467b-bff6-5350a0af19fc"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Metaheuristics = "bcdb8e00-2c21-11e9-3065-2b553b22f898"
ModelContextProtocol = "c58f755f-f2a7-4f48-bf29-4e9659b78499"
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
Optimization = "7f7a1694-90dd-40f0-9382-eb1efda571ba"
OptimizationBBO = "3e6eede4-6085-4f62-9a71-46d9bc1eb92b"
OptimizationMetaheuristics = "3aafef2f-86ae-4776-b337-85a36adf0b55"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Redis = "0cf705f9-a9e2-50d1-a699-2b372a39b750"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
URIs = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[compat]
CSV = "0.10.15"
ComponentArrays = "0.15.30"
DataFrames = "1.8.1"
DataInterpolations = "8.8.0"
Dates = "1.11.0"
DotEnv = "1.0.0"
GlobalSensitivity = "2.10.0"
JSON3 = "1.14.3"
Metaheuristics = "3.4.2"
ModelContextProtocol = "0.4.0"
NPZ = "0.4.3"
Optimisers = "0.4.7"
Optimization = "5.5.0"
OptimizationBBO = "0.4.6"
OptimizationMetaheuristics = "0.3.5"
Plots = "1.41.6"
Redis = "3.0.0"
SciMLBase = "2.138.0"
Statistics = "1.11.1"
StatsBase = "0.34.10"
Test = "1.11.0"
URIs = "1.6.1"
