name = "HydroModelMCP"
uuid = "b04cb046-4fd7-4b4f-8949-f07de8180241"
version = "0.1.0"
authors = ["jing xin <50790703+chooron@users.noreply.github.com>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataInterpolations = "82cc6244-b520-54b8-b5a6-8a565e85f1d0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HydroModelLibrary = "f34bc7f3-9d04-4ef8-b7a3-feb87ce2ba93"
HydroModels = "7e3cde01-c141-467b-bff6-5350a0af19fc"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
ModelContextProtocol = "c58f755f-f2a7-4f48-bf29-4e9659b78499"
Redis = "0cf705f9-a9e2-50d1-a699-2b372a39b750"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
CSV = "0.10.15"
ComponentArrays = "0.15.30"
DataFrames = "1.8.1"
DataInterpolations = "8.8.0"
Dates = "1.11.0"
HydroModelLibrary = "0.1.2"
HydroModels = "0.5.1"
JSON3 = "1.14.3"
ModelContextProtocol = "0.4.0"
Redis = "3.0.0"
Statistics = "1.11.1"
Test = "1.11.0"
